version: "3.9"

services:
  web:
    image: nginx:latest
    network_mode: bridge
    ports:
      - 1011:80
    volumes:
      - ./wwwroot:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro